# Description:
#             This is a simple Makefile to compile PANDA in c++
# Authors:
#             Kimberley Glass, Marouen Ben Guebila 05/2019

PANDA: PANDA_v2.c
	g++ -O3 -coverage -o PANDA PANDA_v2.c
	
clean:
	rm *.o *.gcno *.gcda *.pairs
