# Description:
#             This is a simple Makefile to compile PUMA in c++
# Authors:
#             Marieke Kuijjer, Marouen Ben Guebila 10/2019

PANDA: PUMA.c
	g++ -coverage -O3 -o PUMA PUMA.c
	
clean:
	rm *.o *.gcno *.gcda *.pairs
